[versions]
version = "2.2.2"
androidx-activityCompose = "1.11.0"
compose = "1.9.3"
kotlin = "2.2.21"
dokka = "2.1.0"
mavenPublish = "0.35.0"
agp = "8.11.0"
arrow = "2.2.0"
kotlinx-coroutines = "1.10.2"
kermit = "2.0.8"
buildKonfig = "0.17.1"
kotlinx-immutable = "0.4.0"

[libraries]
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
arrow-core = { group = "io.arrow-kt", name = "arrow-core", version.ref = "arrow" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }